name: Check and Plan - NFT
on:
  pull_request:
    branches:
      - nft

jobs:
  check-and-plan:
    name: Check and Plan
    uses: ./.github/workflows/check-and-plan.yml
    with:
      environment: nft
      aws-account-id: 448120078528
